spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
server:
  servlet:
    context-path: /act/api
  cors:
    origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

#configuração swagger
springdoc:
  swagger-ui:
    path: /public/swagger